# Generated by Django 2.1 on 2023-08-01 06:21

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mode',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 1, 6, 21, 21, 976470, tzinfo=utc)),
        ),
    ]
