# Generated by Django 2.1 on 2023-08-01 06:22

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_mode_date_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mode',
            name='date_created',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
