# Generated by Django 2.1 on 2023-08-01 08:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0003_auto_20230801_0622'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Mode',
            new_name='Movie',
        ),
    ]
